<a href="https://colab.research.google.com/github/misspresident-codes/DecodeLabs-Internship/blob/main/Project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
data = pd.read_csv('/content/fraudTest.csv')

In [7]:
df = pd.DataFrame(data)

In [8]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0.0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0.0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0.0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0.0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0.0

In [9]:
df.tail()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
461261,461261,2020-12-11 05:15:30,4900628639996,"fraud_Schoen, Kuphal and Nitzsche",grocery_pos,46.50,Michael,Johnson,M,094 Owens Underpass,...,33.9056,-118.0818,105549,Firefighter,1973-09-22,1e5cfc15cdf53aa74bd30ab661ac259b,1386738930,34.317071,-117.164998,0.0
461262,461262,2020-12-11 05:16:23,630469040731,fraud_Koepp-Witting,grocery_pos,115.39,Meredith,Ayala,F,7107 Henderson Station,...,45.6710,-121.8686,1288,Barrister,1936-05-01,efbcc864efcf7756dcbb964fccffb548,1386738983,46.630229,-122.097308,0.0
461263,461263,2020-12-11 05:16:27,3596217206093829,fraud_Stracke-Lemke,grocery_pos,392.00,Sara,Ramirez,F,23843 Scott Island,...,40.8626,-91.9534,888,Camera operator,1988-03-25,0dda73ba1f5adbd7b92c0b7f1f0b0c2a,1386738987,40.742460,-92.531863,1.0
461264,461264,2020-12-11 05:17:02,4610064888664703,"fraud_Swift, Bradtke and Marquardt",grocery_net,86.68,Tammy,Maldonado,F,3312 Rachel Parks Suite 474,...,43.2229,-75.2899,847,Systems analyst,1996-01-11,5db65efd5f50712c91d9941316b82fb3,1386739022,43.466131,-75.662295,0.0
461265,461265,2020-12-11 05:17:04,4302480582202074,"fraud_Zieme, Bode and Dooley",gas_transport,48.76,David,Rodriguez,M,821 Solis Points,...,43.2326,-86.2492,128715,Historic buildings inspector/conservation officer,1995-05-25,a6b8b33e60e79183ce9b6d123aed8c07,1386739024,44.016349,-85.000000,NaN

In [11]:
df.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,461266.000000,4.612660e+05,461266.000000,461266.000000,461266.000000,461266.000000,4.612660e+05,4.612660e+05,461266.000000,461266.000000,461265.000000
mean,230632.500000,4.187036e+17,69.507467,48832.475346,38.541785,-90.227806,8.827129e+04,1.379255e+09,38.541615,-90.227510,0.004399
std,133156.168971,1.311093e+18,148.985642,26854.423705,5.060941,13.722138,3.002937e+05,4.539538e+06,5.095599,13.734357,0.066177
min,0.000000,6.041621e+10,1.000000,1257.000000,20.027100,-165.672300,2.300000e+01,1.371817e+09,19.027422,-166.671575,0.000000
25%,115316.250000,1.800429e+14,9.630000,26237.000000,34.668900,-96.798000,7.410000e+02,1.375297e+09,34.756184,-96.898405,0.000000
50%,230632.500000,3.521417e+15,47.340000,48174.000000,39.371600,-87.476900,2.408000e+03,1.378989e+09,39.376919,-87.443145,0.000000
75%,345948.750000,4.642255e+15,83.090000,72011.000000,41.894800,-80.175200,1.968500e+04,1.383342e+09,41.951405,-80.258426,0.000000
max,461265.000000,4.992346e+18,19364.910000,99921.000000,65.689900,-67.950300,2.906700e+06,1.386739e+09,66.679297,-66.952026,1.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 461266 entries, 0 to 461265
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             461266 non-null  int64
 1   trans_date_trans_time  461266 non-null  object
 2   cc_num                 461266 non-null  int64
 3   merchant               461266 non-null  object
 4   category               461266 non-null  object
 5   amt                    461266 non-null  float64
 6   first                  461266 non-null  object
 7   last                   461266 non-null  object
 8   gender                 461266 non-null  object
 9   street                 461266 non-null  object
 10  city                   461266 non-null  object
 11  state                  461266 non-null  object
 12  zip                    461266 non-null  int64
 13  lat                    461266 non-null  float64
 14  long                   461266 non-null  float64
 15  city_pop               461266 non-null  int64
 16  job                    461266 non-null  object
 17  dob                    461266 non-null  object
 18  trans_num              461266 non-null  object
 19  unix_time              461266 non-null  int64
 20  merch_lat              461266 non-null  float64
 21  merch_long             461266 non-null  float64
 22  is_fraud               461265 non-null  float64
dtypes: float64(6), int64(5), object(12)
memory usage: 80.9+ MB

In [12]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 1
dtype: int64